In [1]:
import torch
from torch import nn

In [7]:
x = torch.randn(3, 7)
relu_layer = nn.ReLU()

print(x)
print(relu_layer(x))

tensor([[ 1.0245, -1.0011,  0.1725,  2.1810,  0.3666, -1.2172,  1.7426],
        [ 0.2090, -1.1235, -0.3705, -0.0974, -0.9140,  0.8615, -0.0692],
        [ 1.5135, -0.4935,  2.1390, -0.4448, -0.3071,  0.2593,  1.0153]])
tensor([[1.0245, 0.0000, 0.1725, 2.1810, 0.3666, 0.0000, 1.7426],
        [0.2090, 0.0000, 0.0000, 0.0000, 0.0000, 0.8615, 0.0000],
        [1.5135, 0.0000, 2.1390, 0.0000, 0.0000, 0.2593, 1.0153]])


In [8]:
x = torch.randn(3, 5)
drop_layer = nn.Dropout(p=0.3) # 죽일 확률

print(x)
print(drop_layer(x)) # data 각각마다 drop할지 결정 (epoch, batch 아님)

tensor([[ 1.5115,  0.2760,  0.1465, -0.4625,  0.0029],
        [-0.8595, -1.7360, -0.0095,  0.8416, -0.3051],
        [ 0.2812, -0.0274,  0.1484,  0.2267,  0.1550]])
tensor([[ 2.1593,  0.3943,  0.2093, -0.0000,  0.0041],
        [-0.0000, -2.4800, -0.0000,  0.0000, -0.4358],
        [ 0.0000, -0.0391,  0.2121,  0.3238,  0.0000]])


In [11]:
class DropOutMLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer = nn.Sequential(
            nn.Linear(3, 5),
            nn.Dropout(p=0.3)
        )
    
    def forward(self, x):
        return self.layer(x)

x= torch.randn(2, 3)
model = DropOutMLP()

model.train()
print(model(x))

model.eval() # 값에 살릴 확률인 0.7이 곱해진다.
print(model(x))

tensor([[-1.1938,  0.0000, -0.0000, -0.5976, -1.6976],
        [ 0.2718,  0.8132, -0.2879, -0.8741, -0.4319]], grad_fn=<MulBackward0>)
tensor([[-0.8357,  0.3139, -0.5737, -0.4183, -1.1883],
        [ 0.1903,  0.5692, -0.2015, -0.6119, -0.3023]],
       grad_fn=<AddmmBackward0>)


In [15]:
x = torch.randn(1, 100, 100) #채 행 열
conv_layer = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3)

output = conv_layer(x)
print(output.shape) # (3, 98, 98) (채 행 열)

torch.Size([3, 98, 98])


In [19]:
x = torch.randn(32, 1, 100, 100) # (개 채 행 열)
conv_layer = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3)

output = conv_layer(x)
print(output.shape) # (32, 3, 98, 98) (개 채 행 열)
print(conv_layer.weight.shape)

torch.Size([32, 3, 98, 98])
torch.Size([3, 1, 3, 3])


In [17]:
x = torch.randn(32, 1, 100, 100) # (개 채 행 열)
conv_layer = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3, padding=1)

output = conv_layer(x)
print(output.shape) # (32, 3, 100, 100) (개 채 행 열)

torch.Size([32, 3, 100, 100])


In [22]:
layer = nn.Conv2d(5, 10, 3)
print(layer.weight.shape) # (10, 5, 3, 3)
print(layer.bias.shape) # (10,)

torch.Size([10, 5, 3, 3])
torch.Size([10])


In [26]:
x = torch.randn(32, 3, 100, 100)
conv1 = nn.Conv2d(3, 10, 3, padding=1)

x = conv1(x)
print(x.shape) # (32, 10, 100, 100)

conv2 = nn.Conv2d(10, 20, 3, padding=1)
x = conv2(x)
print(x.shape) # (32, 20, 100, 100)

maxpool = nn.MaxPool2d(kernel_size=2, stride=(2, 2))
x = maxpool(x)
print(x.shape) # (32, 20, 50, 50)

torch.Size([32, 10, 100, 100])
torch.Size([32, 20, 100, 100])
torch.Size([32, 20, 50, 50])
