### numpy와 닮은 pytorch

In [8]:
import torch

arr_1 = torch.tensor([1, 2, 3, 4])
print(arr_1)
print(type(arr_1))
print(arr_1.shape)
print(arr_1.dtype, '\n')

arr_2 = torch.tensor([1.0, 2, 3, 4])
print(arr_2)
print(arr_2.dtype)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.Size([4])
torch.int64 

tensor([1., 2., 3., 4.])
torch.float32


In [16]:
import torch

arr_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(arr_1)
print(arr_1.shape)
print(arr_1.numel()) # 전체 성분의 개수
print(arr_1.ndim) # 차원의 크기
print(arr_1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
6
2
torch.int64


In [19]:
print(torch.zeros(5))
print(torch.zeros_like(arr_1), '\n')

print(torch.ones(5))
print(torch.ones((2, 3)), '\n')

print(torch.arange(3, 10, 2))
print(torch.arange(0, 1, 0.1))

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0, 0],
        [0, 0, 0]]) 

tensor([1., 1., 1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])


In [21]:
arr_1 = torch.tensor([1, 2, 3])
arr_2 = torch.tensor([4, 5, 6])
print(arr_1 + arr_2)

tensor([5, 7, 9])


In [22]:
arr_1 = torch.tensor([[1, 2, 3], [1, 2, 3]])
arr_2 = torch.tensor([[4, 5, 6], [4, 5, 6]])

print(arr_1 + arr_2)
print(arr_1 - arr_2)
print(arr_1 * arr_2)
print(arr_1 / arr_2)
print(arr_2**2)

tensor([[5, 7, 9],
        [5, 7, 9]])
tensor([[-3, -3, -3],
        [-3, -3, -3]])
tensor([[ 4, 10, 18],
        [ 4, 10, 18]])
tensor([[0.2500, 0.4000, 0.5000],
        [0.2500, 0.4000, 0.5000]])
tensor([[16, 25, 36],
        [16, 25, 36]])


In [23]:
arr1 = torch.tensor([[1,2], [3,4]])
arr2 = torch.tensor([[1,2], [3,4]])

print(arr1*arr2)
print(arr1@arr2) # 진짜 행렬 곱
print(torch.matmul(arr1, arr2)) # 행렬 곱

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])
tensor([[ 7, 10],
        [15, 22]])


In [24]:
arr = torch.tensor([1,2,3,4,5,6,7,8,9])

print(arr)
print(arr[-1])
print(arr[1:4])
print(arr[7:])
print(arr[:7])
print(arr[:])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [35]:
arr = torch.tensor([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

print(arr[:2, 1:3])
print(arr[1:, 0:2])
print(arr[:, 2])

tensor([[2, 3],
        [5, 6]])
tensor([[4, 5],
        [7, 8]])
tensor([3, 6, 9])


In [37]:
arr = torch.tensor([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], 
                    [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]])

print(arr)
print(arr.shape)
print(arr[:1, 1:3, :2])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor([[[4, 5],
         [8, 9]]])


In [41]:
# boolean indexing
arr = torch.tensor([[1,2,3,4], [5,3,7,3]])

print(arr==3)
print(arr[arr==3])

# 3인 성분이 100으로 바뀜
arr[arr==3] = 100
print(arr)

tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])


### Pytorch의 여러 함수들

In [43]:
arr_1 = torch.randn(3, 3) # 정규분포로 랜덤 값 생성
arr_2 = torch.rand(3, 3) # 0~1 사이를 균일분포로 랜덤 값 생성

print(arr_1)
print(arr_2)

tensor([[ 1.1895, -1.0632,  1.2350],
        [ 0.2575, -0.6246,  0.9746],
        [ 0.9691,  0.3443, -1.2394]])
tensor([[0.7537, 0.7286, 0.2977],
        [0.8097, 0.9797, 0.5920],
        [0.0657, 0.0413, 0.7726]])


In [46]:
arr = torch.randn(2, 3)

print(arr)
print(torch.abs(arr))
print(torch.sqrt(torch.abs(arr)))

tensor([[-1.8099, -0.1103, -0.0494],
        [ 1.6108,  0.6934, -0.8672]])
tensor([[1.8099, 0.1103, 0.0494],
        [1.6108, 0.6934, 0.8672]])
tensor([[1.3453, 0.3320, 0.2222],
        [1.2692, 0.8327, 0.9312]])


In [48]:
arr = torch.randn(2, 3)
print(arr)
print(torch.argmax(arr)) # 가장 큰 요소가 있는 index를 출력하라

tensor([[-2.3371,  1.2128, -1.4655],
        [ 0.6913, -0.7069, -1.5811]])
tensor(1)


In [55]:
arr = torch.randn(3, 4)

print(arr)
print(torch.max(arr), end='\n\n')
print(torch.max(arr, dim=0), end='\n\n')
print(torch.max(arr, dim=1), end='\n\n')
print(torch.max(arr, dim=1, keepdim=True), end='\n\n')

print(arr.max(), end='\n\n')
print(arr.max(dim=0), end='\n\n')
print(arr.max(dim=1), end='\n\n')
print(arr.max(dim=1, keepdim=True), end='\n\n')

tensor([[-1.7716, -0.8756,  0.2048, -0.8494],
        [ 1.3788, -0.6281,  0.6195,  0.3631],
        [-0.1620, -0.1821,  0.1285,  1.6756]])
tensor(1.6756)

torch.return_types.max(
values=tensor([ 1.3788, -0.1821,  0.6195,  1.6756]),
indices=tensor([1, 2, 1, 2]))

torch.return_types.max(
values=tensor([0.2048, 1.3788, 1.6756]),
indices=tensor([2, 0, 3]))

torch.return_types.max(
values=tensor([[0.2048],
        [1.3788],
        [1.6756]]),
indices=tensor([[2],
        [0],
        [3]]))

tensor(1.6756)

torch.return_types.max(
values=tensor([ 1.3788, -0.1821,  0.6195,  1.6756]),
indices=tensor([1, 2, 1, 2]))

torch.return_types.max(
values=tensor([0.2048, 1.3788, 1.6756]),
indices=tensor([2, 0, 3]))

torch.return_types.max(
values=tensor([[0.2048],
        [1.3788],
        [1.6756]]),
indices=tensor([[2],
        [0],
        [3]]))



In [57]:
arr = torch.randn(12,)

print(arr)
print(arr.shape)

arr = arr.reshape(2, 3, 2)
print(arr)
print(arr.shape)

tensor([ 0.8400,  0.8497, -1.4448, -0.9304, -1.4785,  1.2500, -1.1463,  1.6735,
        -1.5581, -0.5516,  0.7348,  2.4482])
torch.Size([12])
tensor([[[ 0.8400,  0.8497],
         [-1.4448, -0.9304],
         [-1.4785,  1.2500]],

        [[-1.1463,  1.6735],
         [-1.5581, -0.5516],
         [ 0.7348,  2.4482]]])
torch.Size([2, 3, 2])


In [58]:
arr1 = torch.tensor([1, 2, 3])
arr2 = torch.tensor([2, 3, 4])

arr1 = arr1.reshape(3, 1)
arr2 = arr2.reshape(3, 1)

print(torch.matmul(arr1.T, arr2))

tensor([[20]])


### torch <-> numpy

In [59]:
import numpy as np
import torch

a = np.array([1, 2, 3])
b = torch.tensor([4, 5, 6])

torch_a = torch.tensor(a)
print(torch_a)
print(type(torch_a))

np_b = b.numpy()
print(np_b)
print(type(np_b))

tensor([1, 2, 3], dtype=torch.int32)
<class 'torch.Tensor'>
[4 5 6]
<class 'numpy.ndarray'>
