### Pytorch의 autograd

In [2]:
import torch

x = torch.tensor([3.0], requires_grad=True)

y = x**2
print(y)

y.backward() # 미분의 결과를 x.grad에 넣어준다.
print(x.grad)

tensor([9.], grad_fn=<PowBackward0>)
tensor([6.])


In [3]:
x = torch.tensor([3.0], requires_grad=True)

y = x**2
print(y)

y.backward() # 미분의 결과를 x.grad에 넣어준다.
print(x.grad)

tensor([9.], grad_fn=<PowBackward0>)
tensor([6.])


In [4]:
x = torch.tensor([3.0], requires_grad=True)

y = x**2
z = 3*y

z.backward() # 미분의 결과를 x.grad에 넣어준다.
print(x.grad)

tensor([18.])


In [5]:
x = torch.tensor([3.0], requires_grad=True)

a = x**2
b = a+1

b.backward()
print(x.grad)

tensor([6.])


In [6]:
x = torch.tensor([3.0], requires_grad=True)

a = x**2
b = a+1
c = b**2

# 2b*1*2x = 2*10*1*2*3 = 120
c.backward()
print(x.grad)

tensor([120.])


In [7]:
x = torch.tensor([3.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)

z = 2*x**2 + y**2

z.backward()

# 편미분
print(x.grad) # 4x = 12
print(y.grad) # 2y = 4

tensor([12.])
tensor([4.])


In [8]:
x = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)
y = torch.sum(3*x**2)

y.backward()
print(x.grad)

tensor([12., 18., 24.])


In [9]:
x = torch.tensor([2.0, 3.0, 4.0], requires_grad=True)
y = torch.mean(x**2)

y.backward()
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])
