### Simple Linear Neural Network

In [19]:
import torch
from torch import nn

x = torch.tensor([[1], [2]], dtype=torch.float)

model = nn.Linear(1, 1)
print(model.weight)
print(model.bias, end='\n\n')

output = model(x)
print(output)

output = torch.matmul(x, model.weight) + model.bias
print(output)

Parameter containing:
tensor([[-0.7998]], requires_grad=True)
Parameter containing:
tensor([0.3761], requires_grad=True)

tensor([[-0.4237],
        [-1.2235]], grad_fn=<AddmmBackward0>)
tensor([[-0.4237],
        [-1.2235]], grad_fn=<AddBackward0>)


In [29]:
fc1 = nn.Linear(3, 1)
fc2 = nn.Linear(1, 3)

print(fc1.weight)
print(fc1.bias, end='\n\n')

print(fc2.weight)
print(fc2.bias, end='\n\n')

x = torch.tensor([1., 2., 3.])
output1 = fc1(x)
print(output1)

output1_2 = torch.matmul(x, fc1.weight.T) + fc1.bias
print(output1_2, end='\n\n')

x = torch.tensor([1.])
output2 = fc2(x)
print(output2)

output2_2 = torch.matmul(x, fc2.weight.T) + fc2.bias
print(output2_2)

Parameter containing:
tensor([[ 0.3333,  0.0327, -0.5470]], requires_grad=True)
Parameter containing:
tensor([-0.2812], requires_grad=True)

Parameter containing:
tensor([[-0.8528],
        [-0.4689],
        [-0.8654]], requires_grad=True)
Parameter containing:
tensor([ 0.8622,  0.4143, -0.2668], requires_grad=True)

tensor([-1.5236], grad_fn=<ViewBackward0>)
tensor([-1.5236], grad_fn=<AddBackward0>)

tensor([ 0.0093, -0.0546, -1.1322], grad_fn=<ViewBackward0>)
tensor([ 0.0093, -0.0546, -1.1322], grad_fn=<AddBackward0>)


In [34]:
import torch
from torch import nn

layer = nn.Sequential(
            nn.Linear(3, 10),
            nn.Linear(10, 2)
        )

x = torch.randn(5, 3)
print(layer(x))

tensor([[-0.4022, -0.4297],
        [-0.4134, -0.1090],
        [-0.1414,  0.1632],
        [-0.0864,  0.3043],
        [-0.2313,  0.0289]], grad_fn=<AddmmBackward0>)


In [70]:
import torch
from torch import nn

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Sequential(
                        nn.Linear(2, 5),
                        nn.Sigmoid())

        self.layer2 = nn.Sequential(
                        nn.Linear(5, 10),
                        nn.Sigmoid())
        
        self.layer3 = nn.Sequential(
                        nn.Linear(10, 3),
                        nn.Sigmoid())

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

model = CustomModel()
x = torch.randn(5, 2)
output = model(x)
print(output)

tensor([[0.5758, 0.5638, 0.5112],
        [0.5740, 0.5676, 0.5134],
        [0.5755, 0.5645, 0.5115],
        [0.5756, 0.5648, 0.5131],
        [0.5740, 0.5676, 0.5134]], grad_fn=<SigmoidBackward0>)


In [71]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.1168, -0.3809],
        [-0.2515, -0.6703],
        [ 0.5749,  0.1408],
        [ 0.2429, -0.5906],
        [ 0.0744, -0.5383]], requires_grad=True), Parameter containing:
tensor([ 0.0912,  0.4546,  0.3412, -0.7037, -0.0356], requires_grad=True), Parameter containing:
tensor([[ 0.0612,  0.2181,  0.1192,  0.0938,  0.2089],
        [-0.0974, -0.2286, -0.1097,  0.0526,  0.2807],
        [ 0.3228,  0.0586,  0.2685, -0.4358, -0.2893],
        [ 0.2752,  0.3000,  0.2130,  0.1380, -0.3325],
        [-0.1186,  0.3304,  0.1666, -0.3408,  0.4132],
        [ 0.1533, -0.3811, -0.2708,  0.2397,  0.3969],
        [ 0.4223,  0.0592,  0.2980, -0.4051,  0.0282],
        [-0.2962,  0.3934,  0.0282,  0.3628,  0.2609],
        [-0.4110,  0.0996, -0.2796, -0.0783, -0.0644],
        [ 0.1412, -0.0319, -0.1629, -0.1590, -0.2354]], requires_grad=True), Parameter containing:
tensor([-0.2466,  0.2079,  0.3312,  0.2855,  0.3585, -0.2896,  0.2212,  0.3589,
        -0.0120,  0.42

### Weight Initialization

In [72]:
import torch
from torch import nn

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer1 = nn.Sequential(
                        nn.Linear(2, 5),
                        nn.Sigmoid())

        self.layer2 = nn.Sequential(
                        nn.Linear(5, 10),
                        nn.Sigmoid())
        
        self.layer3 = nn.Sequential(
                        nn.Linear(10, 3),
                        nn.Sigmoid())

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_normal_(m.weight.data)
                m.bias.data.fill_(0)

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        return x

print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.1168, -0.3809],
        [-0.2515, -0.6703],
        [ 0.5749,  0.1408],
        [ 0.2429, -0.5906],
        [ 0.0744, -0.5383]], requires_grad=True), Parameter containing:
tensor([ 0.0912,  0.4546,  0.3412, -0.7037, -0.0356], requires_grad=True), Parameter containing:
tensor([[ 0.0612,  0.2181,  0.1192,  0.0938,  0.2089],
        [-0.0974, -0.2286, -0.1097,  0.0526,  0.2807],
        [ 0.3228,  0.0586,  0.2685, -0.4358, -0.2893],
        [ 0.2752,  0.3000,  0.2130,  0.1380, -0.3325],
        [-0.1186,  0.3304,  0.1666, -0.3408,  0.4132],
        [ 0.1533, -0.3811, -0.2708,  0.2397,  0.3969],
        [ 0.4223,  0.0592,  0.2980, -0.4051,  0.0282],
        [-0.2962,  0.3934,  0.0282,  0.3628,  0.2609],
        [-0.4110,  0.0996, -0.2796, -0.0783, -0.0644],
        [ 0.1412, -0.0319, -0.1629, -0.1590, -0.2354]], requires_grad=True), Parameter containing:
tensor([-0.2466,  0.2079,  0.3312,  0.2855,  0.3585, -0.2896,  0.2212,  0.3589,
        -0.0120,  0.42